"""empty message

Revision ID: 1b7bc73e2323
Revises: f2d2c422f104
Create Date: 2024-06-20 10:35:36.808657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7bc73e2323'
down_revision = 'f2d2c422f104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('show_id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('director', sa.String(length=200), nullable=True),
    sa.Column('cast', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('date_added', sa.String(length=100), nullable=True),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('listed_in', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('is_adult', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=200), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('num_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_table('series',
    sa.Column('show_id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('director', sa.String(length=200), nullable=True),
    sa.Column('cast', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('date_added', sa.String(length=100), nullable=True),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('listed_in', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('is_adult', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=200), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('num_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('show_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    op.drop_table('movies')
    # ### end Alembic commands ###
