"""empty message

Revision ID: 1fef5af197fe
Revises: 87d51269ef69
Create Date: 2024-07-02 23:14:49.307252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fef5af197fe'
down_revision = '87d51269ef69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
