"""empty message

Revision ID: 255a9d32fcfc
Revises: 9a826ae4e7e0
Create Date: 2024-06-23 20:07:52.480959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255a9d32fcfc'
down_revision = '9a826ae4e7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_user_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_rated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('serie_user_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_rated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serie_user_ratings', schema=None) as batch_op:
        batch_op.drop_column('date_rated')

    with op.batch_alter_table('movie_user_ratings', schema=None) as batch_op:
        batch_op.drop_column('date_rated')

    # ### end Alembic commands ###
