"""empty message

Revision ID: 5b8673c3821b
Revises: 62b34ffa4df7
Create Date: 2024-06-20 22:38:46.508243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8673c3821b'
down_revision = '62b34ffa4df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)

    # ### end Alembic commands ###
