"""empty message

Revision ID: 62b34ffa4df7
Revises: 040c160be611
Create Date: 2024-06-20 22:37:11.276330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b34ffa4df7'
down_revision = '040c160be611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('director', sa.String(length=300), nullable=True),
    sa.Column('cast', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=300), nullable=True),
    sa.Column('date_added', sa.String(length=100), nullable=True),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('listed_in', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('is_adult', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=300), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('num_votes', sa.Integer(), nullable=True),
    sa.Column('spoken_languages', sa.String(length=50), nullable=True),
    sa.Column('original_language', sa.String(length=50), nullable=True),
    sa.Column('poster_url', sa.String(length=300), nullable=True),
    sa.Column('youtube_trailers', sa.String(length=1000), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('director', sa.String(length=300), nullable=True),
    sa.Column('cast', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=300), nullable=True),
    sa.Column('date_added', sa.String(length=100), nullable=True),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('listed_in', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('is_adult', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=300), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('num_votes', sa.Integer(), nullable=True),
    sa.Column('spoken_languages', sa.String(length=50), nullable=True),
    sa.Column('original_language', sa.String(length=50), nullable=True),
    sa.Column('seasons', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=300), nullable=True),
    sa.Column('youtube_trailers', sa.String(length=1000), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    op.drop_table('movies')
    # ### end Alembic commands ###
