"""empty message

Revision ID: 871226a92956
Revises: 9043de3180aa
Create Date: 2024-06-23 20:32:38.125189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871226a92956'
down_revision = '9043de3180aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
