"""empty message

Revision ID: 87d51269ef69
Revises: 871226a92956
Create Date: 2024-06-26 19:29:01.910394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d51269ef69'
down_revision = '871226a92956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_new_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new_user', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
