"""empty message

Revision ID: b236e1aad03a
Revises: e2f86e5a503c
Create Date: 2024-07-02 23:28:28.983231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b236e1aad03a'
down_revision = 'e2f86e5a503c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('date_added')
        batch_op.drop_column('is_adult')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_adult', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_added', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
