"""empty message

Revision ID: e2f86e5a503c
Revises: 1fef5af197fe
Create Date: 2024-07-02 23:27:06.275006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f86e5a503c'
down_revision = '1fef5af197fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('is_adult')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_adult', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
